title: AWS Certified AI Practitioner
email: vusirikalaharikiran@gmail.com
description: Preparation for clearing AWS Certified AI Practitioner
theme: just-the-docs

url: https://harikiranvusirikala.github.io/aws-certified-ai-practitioner

# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/images/icon.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Build settings
# aux_links: # remove if you don't want this link to appear on your pages
#   Repository: https://github.com/harikiranvusirikala/aws-certified-ai-practitioner
# aux_links_new_tab: true
# heading_anchors: true     # true is default
footer_content: 'Contact over LinkedIn at <a href="https://linkedin.com/in/hari-kiran-vusirikala/">Hari Kiran Vusirikala</a>'

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: red
  alert:
    color: yellow
  note:
    title: Note
    color: purple

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-F3R5F3MBEK
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# For copy button on code
enable_copy_code_button: true
